package com.marketradar.app

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

class BatchACapturePersistenceTest {
    @Test fun actualPythonOpenPositionSnapshotSurvivesAndroidPersistenceHop() {
        // Generated by brain.take_poll_snapshot(..., "android_compact_v1")
        // with one synthetic open Paper position; only Batch A context retained.
        val text = requireNotNull(javaClass.classLoader?.getResourceAsStream(
            "contracts/b490_python_take_poll_snapshot_open_position.json"
        )).bufferedReader().use { it.readText() }
        val raw = JSONObject(text)
        val source = raw.getJSONObject("context_json")
        assertTrue(source.getJSONObject("snapshot_position_verdicts").has("paper-284"))
        val compact = EvaluationLocalCache.compactBrainSnapshotForPersistence(raw)
        val retained = compact.getJSONObject("context_json")
        for (key in EvaluationLocalCache.BATCH_A_CONTEXT_KEYS) {
            if (source.has(key)) {
                assertTrue("missing $key", retained.has(key))
                assertEquals("changed $key", source.get(key).toString(), retained.get(key).toString())
            }
        }
        assertEquals("forward_capture_v1_batch_a", retained.getString("snapshot_capture_completeness"))
    }

    @Test fun optionalBatchAObjectsScalarsAndArraysSurviveWhenPresent() {
        val source = JSONObject()
        for (key in EvaluationLocalCache.BATCH_A_CONTEXT_KEYS) {
            val value = when (key) {
                "snapshot_watchlist", "snapshot_open_trades" -> JSONArray().put("sample")
                "nfDTE", "bnfDTE" -> 0
                "snapshot_open_trades_json", "snapshot_closed_trades_json",
                "snapshot_capture_completeness", "snapshot_capture_failure_reason" -> "sample"
                else -> JSONObject().put("sample", 1)
            }
            source.put(key, value)
        }
        val compact = EvaluationLocalCache.compactBrainSnapshotForPersistence(
            JSONObject().put("context_json", source)
        ).getJSONObject("context_json")
        for (key in EvaluationLocalCache.BATCH_A_CONTEXT_KEYS) {
            assertEquals("changed $key", source.get(key).toString(), compact.get(key).toString())
        }
        assertFalse(compact.isNull("nfDTE"))
    }

    @Test fun kotlinBatchAKeysCoverAllPythonBatchASurvivors() {
        val pythonFile = listOf(File("src/main/python/brain.py"), File("app/src/main/python/brain.py"))
            .first { it.isFile }
        val source = pythonFile.readText()
        val block = source.substringAfter("def _compact_android_snapshot_context(")
            .substringBefore("for key in scalar_keys:")
        val sections = Regex("(?m)^\\s*# Batch A evidence-contract survivors[^\\n]*\\n((?:\\s*'[^']+'[^\\n]*\\n)+)")
            .findAll(block).toList()
        assertEquals("Python scalar, object and array survivor sections", 3, sections.size)
        val pythonKeys = sections.flatMap { section ->
            Regex("'([^']+)'").findAll(section.groupValues[1]).map { it.groupValues[1] }.toList()
        }.toSet()
        assertTrue("Missing Kotlin survivors: ${pythonKeys - EvaluationLocalCache.BATCH_A_CONTEXT_KEYS.toSet()}",
            EvaluationLocalCache.BATCH_A_CONTEXT_KEYS.toSet().containsAll(pythonKeys))
    }
}
